config/routes.rb
Rails.application.routes.draw do
  
  root 'flight#index'
  resources :flight do
  resources :bookings
  end
  resources :bookings
  
  

end

app/models/airport.rb
class Airport < ActiveRecord::Base
has_many :departing_flights, class_name: "Flight", foreign_key: "from_airport_id"
                           
                             
has_many :arriving_flights, class_name: "Flight", foreign_key: "to_airport_id"

validates :airport_code, presence: true

end

app/models/booking.rb
class Booking < ActiveRecord::Base
belongs_to :flight
has_many :passengers, through: :passenger_bookings
has_many :passenger_bookings

accepts_nested_attributes_for :passengers

validates :flight_id, presence: true
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :from_airport, class_name: "Airport"
  belongs_to :to_airport, class_name: "Airport"
  has_many :bookings
  has_many :passengers, :through => :bookings
  validates :to_airport, presence: true
  validates :from_airport, presence: true
  
  
  def flight_date_formatted
    departure_time.strftime("%d/%m/%Y")
  end
  
  def self.search(terms)
    if terms[:flight_date]
      Flight.where('cast(to_airport_id as text) LIKE ? AND cast(from_airport_id as text) LIKE ? AND cast(departure_time as text) BETWEEN ? AND ?', "#{terms[:to_airport_id]}", "#{terms[:from_airport_id]}", "#{terms[:flight_date].to_time.beginning_of_day}","#{terms[:flight_date].to_time.end_of_day}")
    else
      Flight.all
    end
  end


end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
has_many :flights, through: :bookings, :foreign_key => "flight_id"
has_many :bookings, through: :passenger_bookings
has_many :passenger_bookings

validates :name, presence: true
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, format: { with: VALID_EMAIL_REGEX, message: "please enter a valid email address"}
end

app/models/passenger_booking.rb
class PassengerBooking < ActiveRecord::Base
  belongs_to :passenger
  belongs_to :booking
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

def new
  @flight = Flight.find(params[:flight_id])
  @booking = Booking.new
  @passengers = params[:passengers]
  @passengers.to_i.times { @booking.passengers.build }
end

def create
  @booking = Booking.new(booking_params)
  
  if @booking.save
    @booking.update_attribute(:flight_id, params[:flight_id])
    flash[:success] = "Your flight has been booked!"
    @booking.passengers.each do |p|
    
     # PassengerMailer.thank_you_email(p).deliver_later
    end
    redirect_to booking_path(@booking)
  else
    @flight = Flight.find(params[:flight_id])
    @booking.errors.each do |type, message| 
      flash.now[:alert] = " #{type} #{message}"
    end
    render 'new'
  end
end
   
   def show
     @booking = Booking.find(params[:id])
   end
   



private
  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [ :id, :name, :email ] )
    end


end

app/controllers/flight_controller.rb
class FlightController < ApplicationController

def index
  @airports = Airport.all.map { |f| [ f.airport_code, f.id ] }
  @flights = Flight.search(params)
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flight_helper.rb
module FlightHelper
end

app/views/bookings/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2>Booking Information</h2>
  </div>
<div class="panel-body">
  <h2><%= "#{@flight.from_airport.airport_code} => #{@flight.to_airport.airport_code}" %></h2>
  
  <p><%= "Flight # #{params[:flight_id]} " %></p>
  <p><%= "Departing from #{@flight.from_airport.airport_code}" %></p>
  <p>on <%= "#{@flight.departure_time.strftime("%B #{@flight.departure_time.day.ordinalize}, %Y")}" %> </p>
  <p><%= "Arriving at #{@flight.to_airport.airport_code}" %></p>
  <p><%= "Estimated flight time of #{@flight.duration} minutes" %></p>
</div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h2>Passenger Information</h2>
  </div>
  <div class="panel-body">
    <%= form_for @booking do |flight|%>
       <%= flight.fields_for :passengers do |passenger| %>

        <%= passenger.label :name, "Name:" %>
        <%= passenger.text_field :name %>
        <%= passenger.label :email, "Email:" %>
        <%= passenger.email_field :email %>
        <br>
        <% end %>
      <%= hidden_field_tag(:passengers, params[:passengers]) %>
      <%= flight.hidden_field :flight_id, value: params[:flight_id] %>
      <%= hidden_field_tag(:flight_id, params[:flight_id]) %>
    
      <%= flight.submit "Submit Passenger Info ",  class: 'btn btn-primary '  %>
      <% end %>
    </div>

</div>

app/views/bookings/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Thanks for booking with Flight Booker </h3>
  </div>
  <div class="panel-body">

    <h3>Flight Details : </h3>
    <div class= "flight-detail" %>
    <p><%= "Flight # :  #{@booking.flight_id} " %></p>
    <p><%= "Departing from :  #{@booking.flight.to_airport.airport_code}" %></p>
    <p>on :  <%= "#{@booking.flight.departure_time.strftime("%B #{@booking.flight.departure_time.day.ordinalize}, %Y")}" %> </p>
    <p><%= "Arriving at :  #{@booking.flight.from_airport.airport_code}" %></p>
    <p><%= "Estimated flight time of :  #{@booking.flight.duration} minutes" %></p>

    <p>Passengers in your Party </p>
    <% @booking.passengers.each do |p| %>
    <ul>
      <li><%= "     #{p.name}" %></li>  
    </ul>
    <% end %>
  </div>
</div>

app/views/flight/_results.html.erb
<div class="flight-result">
    <% unless @flights.nil? %>
    <h2>Flights</h2>
    <%= form_for(@booking) do  %>
        <ul> 
          <% @flights.each do |f| %>
            <li><%= radio_button_tag( :flight_id, f.id ) %>
            <%= label :flight, "#{f.departure_time.strftime("%I:%M:%S %p")}" %></li>
          <% end %>
          <%= hidden_field_tag(:passengers, params[:passengers]) %>
        <%= submit_tag( "Book this flight") %>
      <% end %>
    </ul>
    <% end %>
</div>

app/views/flight/index.html.erb
<% if params[:passengers].nil? %>
  <div class="jumbotron flight-table">
    <h1>Welcome to FlightBooker</h1>
    <p>Search for flights below to get started!</p>

  </div>
<% end %>


<div class="search-bar">
<%= form_tag(flight_index_path, method: "get") do %>
  <%= label_tag(:from_airport_id, "Departure Airport:") %>
  <%= select_tag(:from_airport_id, options_for_select(@airports, @from_airport)) %>

  <%= label_tag(:to_airport_id, "Destination Airport:") %>
  <%= select_tag(:to_airport_id, options_for_select(@airports, @to_airport)) %>

  <%= label_tag(:flight_date, "Date of Departure") %>
  <%= select_tag(:flight_date, options_for_select(Flight.all.map { |f| f.flight_date_formatted}.uniq)) %> 
  
  <%= label_tag(:passengers, "Number of Passengers") %>
  <%= select_tag(:passengers, options_for_select(1..4))  %>
  
  <%= submit_tag("Search Flights", :name => nil) %>
<% end %>
</div>

<% unless params[:passengers].nil? %>
<div class="jumbotron jumbotron-inverse flight-table ">
    <h2>Flights</h2>

    <%= form_tag new_booking_path, method: "get" do   %>
        
          <% if @flights.empty? %>
            <p>No flights match your request.</p>
            <% if params[:to_airport_id] == params[:from_airport_id] %>
              <p><small>We have no flights to and from the same airport.</small></p>
            <% end %>
          <% else %>
          <table class="table table-striped">
           
           <tr class="flight-table">
                  <th class="table-fade">Select this Flight</th>
                  <th class="table-fade">Departure Time:</th>
                  <th class="table-fade">Departing from:</th>
                  <th class="table-fade">Destination</th>
                  <th class="table-fade">Flight ID</th>
                </tr>
          <% @flights.each do |f| %>
                <tr>
                   <td><%= radio_button_tag( :flight_id, f.id ) %></td>
                   <td><%= label :flight, "#{f.departure_time.strftime("%I:%M:%S %p")}" %></td>
                   <td><%= Airport.find(f.from_airport_id).airport_code %></td>
                   <td><%= Airport.find(f.to_airport_id).airport_code %></td>
                   <td><%= f.id %></td>
                 </tr>
                   
                <% end %>
            </table>
            <%= hidden_field_tag(:passengers, params[:passengers]) %>
            <%= submit_tag( "Book this flight", class: "submit btn btn-primary") %>

        </ul>
        <% end %>
    <% end %>
</div>
 <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
   <div class="container-fluid">
   <small>
    A Project for <a href="http://www.theodinproject.com/ruby-on-rails/building-advanced-forms">TheOdinProject</a>
    by <a href="https://github.com/Cgipson06">Cody Gipson</a>
  </small>
</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <%= link_to "FlightBooker", root_path, id: "logo" %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlightBooker</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="js/bootstrap.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,200' rel='stylesheet' type='text/css'>
</body>
</html>